### ISSUE TITLE
Improve the damage received when a punch is hit

### ISSUE THREAD

**Issue by angelip2303** [angelip2303/boxing-game#3]
## Todo

- [x]  Refactor the attribute precision changing its name
- [x] Make it work according to a radius
- [x] Parameterize the radius
- [x] Set an interval of time between two consecutive punches
